# TODO find out why it can not be created via API
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    app: telegram-stickers
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/telegram-stickers/data"
