# Generated by Django 3.0.2 on 2020-01-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickerPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_animated', models.BooleanField(default=False)),
                ('installs', models.PositiveIntegerField(default=0)),
                ('tme_url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='')),
                ('sticker_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='core.StickerPack')),
            ],
        ),
    ]
