name: deploy_stage_on_push

on:
  push:
    branches:
      - "develop"
jobs:
#  build_and_publish:
#    runs-on: [ubuntu-latest]
#    env:
#      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
#      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
#      ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
#    steps:
#      - name: login_to_docker.io
#        run:  echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_LOGIN} --password-stdin
#      - name: checkout
#        uses: actions/checkout@v2
#      - name: build_image
#        run: docker build --build-arg ENCRYPT_KEY=${ENCRYPT_KEY} -t $DOCKER_LOGIN/$IMAGE_NAME:latest -f deploy/stage/Dockerfile .
#      - name: push_image_to_docker.io
#        run: docker push $DOCKER_LOGIN/$IMAGE_NAME:latest
  deploy:
    # needs: [build_and_publish]
    runs-on: [ubuntu-latest]
    steps:
      - name: create_secrets_file
        run: echo ${{ secrets.K8S_ENVIRONMENT_SECRETS }} >> env-secrets.yaml
      - name: apply_secrets
        run: >
          curl -X PUT
          -H "Authorization: Bearer ${{ secrets.K8S_TOKEN }}"
          -H "Accept: application/yaml"
          --data-binary @env-secrets.yaml
          ${{ secrets.K8S_URL }}/api/v1/namespaces/default/secrets/environment
